#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TheD.Resource", IsApplication=true)]

namespace TheD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alberto = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int call = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int coaches = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gianni = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int marco = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int omar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sergio = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sessions = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int thediligence = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int albertoButton = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int callOmarButton = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int coachesButton = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int gianniButton = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int imageGianni = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int imageOmar = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int marcoButton = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int omarButton = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int sergioButton = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int sessionsButton = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int textView2 = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CoachesLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GianniLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OmarLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int ApplicationName = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int Coaches = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int alberto = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int gianni = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int marco = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int omar = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int sergio = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Mono_Android_Theme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
